/**
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const Configuration = {
    // The object containing the OAuthToken
    oAuthToken: {},

    // Callback function to be called on token refresh
    // TODO: Replace the oAuthTokenUpdateCallback with an appropriate callback function
    oAuthTokenUpdateCallback: null,

    // The base Uri for API calls
    BASEURI: 'https://slot2.apipractice.t-dev.telstra.net/v2',

    // OAuth 2 Client ID
    // TODO: Replace the OAuthClientId with an appropriate value
    oAuthClientId: 'TODO: Replace',

    // OAuth 2 Client Secret
    // TODO: Replace the OAuthClientSecret with an appropriate value
    oAuthClientSecret: 'TODO: Replace',

};

module.exports = Configuration;
